/*
 * User Manager service
 * Create, retrieve, and manage users and their relationships with internal (DBS services) and external (CRM systems) resources. 
 *
 * The version of the OpenAPI document: 2.6.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.usermanager.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * UserExternal
 */
@JsonPropertyOrder({
  UserExternal.JSON_PROPERTY_EXTERNAL_ID,
  UserExternal.JSON_PROPERTY_LEGAL_ENTITY_EXTERNAL_ID,
  UserExternal.JSON_PROPERTY_FULL_NAME,
  UserExternal.JSON_PROPERTY_PREFERRED_LANGUAGE,
  UserExternal.JSON_PROPERTY_ADDITIONS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:56.279646600+01:00[Africa/Tunis]")
public  class UserExternal {
  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private String externalId;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_EXTERNAL_ID = "legalEntityExternalId";
  private String legalEntityExternalId;

  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  private String fullName;

  public static final String JSON_PROPERTY_PREFERRED_LANGUAGE = "preferredLanguage";
  private String preferredLanguage;

  public static final String JSON_PROPERTY_ADDITIONS = "additions";
  private Map<String, String> additions = null;


  public UserExternal externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * external Id of the user.
   * @return externalId
  **/
  @NotNull
 @Pattern(regexp="^\\S(.*(\\S))?$") @Size(min=1,max=64)  @ApiModelProperty(required = true, value = "external Id of the user.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public UserExternal legalEntityExternalId(String legalEntityExternalId) {
    
    this.legalEntityExternalId = legalEntityExternalId;
    return this;
  }

   /**
   * Legal Entity External Id of the user.
   * @return legalEntityExternalId
  **/
  @NotNull
 @Pattern(regexp="^[^\\r\\n]+$") @Size(min=1,max=64)  @ApiModelProperty(required = true, value = "Legal Entity External Id of the user.")
  @JsonProperty(JSON_PROPERTY_LEGAL_ENTITY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLegalEntityExternalId() {
    return legalEntityExternalId;
  }


  public void setLegalEntityExternalId(String legalEntityExternalId) {
    this.legalEntityExternalId = legalEntityExternalId;
  }


  public UserExternal fullName(String fullName) {
    
    this.fullName = fullName;
    return this;
  }

   /**
   * Full name of the user.
   * @return fullName
  **/
  @NotNull
 @Pattern(regexp="^\\S(.*(\\S))?$") @Size(min=1,max=255)  @ApiModelProperty(required = true, value = "Full name of the user.")
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFullName() {
    return fullName;
  }


  public void setFullName(String fullName) {
    this.fullName = fullName;
  }


  public UserExternal preferredLanguage(String preferredLanguage) {
    
    this.preferredLanguage = preferredLanguage;
    return this;
  }

   /**
   * User preferred language.
   * @return preferredLanguage
  **/
  @javax.annotation.Nullable
 @Size(min=2,max=8)  @ApiModelProperty(value = "User preferred language.")
  @JsonProperty(JSON_PROPERTY_PREFERRED_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreferredLanguage() {
    return preferredLanguage;
  }


  public void setPreferredLanguage(String preferredLanguage) {
    this.preferredLanguage = preferredLanguage;
  }


  public UserExternal additions(Map<String, String> additions) {
    
    this.additions = additions;
    return this;
  }

  public UserExternal putAdditionsItem(String key, String additionsItem) {
    if (this.additions == null) {
      this.additions = new HashMap<>();
    }
    this.additions.put(key, additionsItem);
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getAdditions() {
    return additions;
  }


  public void setAdditions(Map<String, String> additions) {
    this.additions = additions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserExternal userExternal = (UserExternal) o;
    return Objects.equals(this.externalId, userExternal.externalId) &&
        Objects.equals(this.legalEntityExternalId, userExternal.legalEntityExternalId) &&
        Objects.equals(this.fullName, userExternal.fullName) &&
        Objects.equals(this.preferredLanguage, userExternal.preferredLanguage) &&
        Objects.equals(this.additions, userExternal.additions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalId, legalEntityExternalId, fullName, preferredLanguage, additions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserExternal {\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    legalEntityExternalId: ").append(toIndentedString(legalEntityExternalId)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    preferredLanguage: ").append(toIndentedString(preferredLanguage)).append("\n");
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

