/*
 * Arrangement Manager Service API
 * This API allows other DBS services to operate on products
 *
 * The version of the OpenAPI document: 2.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.arrangement.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * AccountStateItem
 */
@JsonPropertyOrder({
  AccountStateItem.JSON_PROPERTY_EXTERNAL_STATE_ID,
  AccountStateItem.JSON_PROPERTY_STATE,
  AccountStateItem.JSON_PROPERTY_DESCRIPTION
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:30:51.050595100+01:00[Africa/Tunis]")
public  class AccountStateItem {
  public static final String JSON_PROPERTY_EXTERNAL_STATE_ID = "externalStateId";
  private String externalStateId;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;


  public AccountStateItem externalStateId(String externalStateId) {
    
    this.externalStateId = externalStateId;
    return this;
  }

   /**
   * unique external identifier for the state
   * @return externalStateId
  **/
  @NotNull
 @Size(min=1,max=50)  @ApiModelProperty(required = true, value = "unique external identifier for the state")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_STATE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalStateId() {
    return externalStateId;
  }


  public void setExternalStateId(String externalStateId) {
    this.externalStateId = externalStateId;
  }


  public AccountStateItem state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * unique identifier for the state. Example: Active
   * @return state
  **/
  @NotNull
 @Size(min=1,max=50)  @ApiModelProperty(required = true, value = "unique identifier for the state. Example: Active")
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public AccountStateItem description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * description of the state
   * @return description
  **/
  @javax.annotation.Nullable
 @Size(max=200)  @ApiModelProperty(value = "description of the state")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountStateItem accountStateItem = (AccountStateItem) o;
    return Objects.equals(this.externalStateId, accountStateItem.externalStateId) &&
        Objects.equals(this.state, accountStateItem.state) &&
        Objects.equals(this.description, accountStateItem.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalStateId, state, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountStateItem {\n");
    sb.append("    externalStateId: ").append(toIndentedString(externalStateId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

