/*
 * Arrangement Manager Service API
 * This API allows other DBS services to operate on products
 *
 * The version of the OpenAPI document: 2.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.arrangement.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.arrangement.service.api.listener.v2.model.AccountPresentationArrangementLegalEntityIds;
import com.microsphere.arrangement.service.api.listener.v2.model.AdditionalProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Container for a list of unique internal Arrangement identifiers.
 */
@ApiModel(description = "Container for a list of unique internal Arrangement identifiers.")
@JsonPropertyOrder({
  AccountArrangementsLegalEntities.JSON_PROPERTY_ARRANGEMENTS_LEGAL_ENTITIES
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:30:51.050595100+01:00[Africa/Tunis]")
public  class AccountArrangementsLegalEntities extends AdditionalProperties {
  public static final String JSON_PROPERTY_ARRANGEMENTS_LEGAL_ENTITIES = "arrangementsLegalEntities";
  private List<AccountPresentationArrangementLegalEntityIds> arrangementsLegalEntities = new ArrayList<>();


  public AccountArrangementsLegalEntities arrangementsLegalEntities(List<AccountPresentationArrangementLegalEntityIds> arrangementsLegalEntities) {
    
    this.arrangementsLegalEntities = arrangementsLegalEntities;
    return this;
  }

  public AccountArrangementsLegalEntities addArrangementsLegalEntitiesItem(AccountPresentationArrangementLegalEntityIds arrangementsLegalEntitiesItem) {
    this.arrangementsLegalEntities.add(arrangementsLegalEntitiesItem);
    return this;
  }

   /**
   * Get arrangementsLegalEntities
   * @return arrangementsLegalEntities
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ARRANGEMENTS_LEGAL_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AccountPresentationArrangementLegalEntityIds> getArrangementsLegalEntities() {
    return arrangementsLegalEntities;
  }


  public void setArrangementsLegalEntities(List<AccountPresentationArrangementLegalEntityIds> arrangementsLegalEntities) {
    this.arrangementsLegalEntities = arrangementsLegalEntities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountArrangementsLegalEntities accountArrangementsLegalEntities = (AccountArrangementsLegalEntities) o;
    return Objects.equals(this.arrangementsLegalEntities, accountArrangementsLegalEntities.arrangementsLegalEntities) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arrangementsLegalEntities, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountArrangementsLegalEntities {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    arrangementsLegalEntities: ").append(toIndentedString(arrangementsLegalEntities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

