/*
 * Arrangement Manager Service API
 * This API allows other DBS services to operate on products
 *
 * The version of the OpenAPI document: 2.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.arrangement.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.arrangement.service.api.listener.v2.model.AdditionalProperties;
import com.microsphere.arrangement.service.api.listener.v2.model.ExternalProductKindItemExtended;
import com.microsphere.arrangement.service.api.listener.v2.model.TranslationItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * AccountProductItem
 */
@JsonPropertyOrder({
  AccountProductItem.JSON_PROPERTY_EXTERNAL_ID,
  AccountProductItem.JSON_PROPERTY_EXTERNAL_TYPE_ID,
  AccountProductItem.JSON_PROPERTY_TYPE_NAME,
  AccountProductItem.JSON_PROPERTY_EXTERNAL_PRODUCT_ID,
  AccountProductItem.JSON_PROPERTY_EXTERNAL_PRODUCT_KIND_ID,
  AccountProductItem.JSON_PROPERTY_PRODUCT_KIND_NAME,
  AccountProductItem.JSON_PROPERTY_EXTERNAL_PRODUCT_TYPE_ID,
  AccountProductItem.JSON_PROPERTY_PRODUCT_TYPE_NAME,
  AccountProductItem.JSON_PROPERTY_PRODUCT_KIND,
  AccountProductItem.JSON_PROPERTY_TRANSLATIONS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:30:51.050595100+01:00[Africa/Tunis]")
public  class AccountProductItem extends AdditionalProperties {
  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private String externalId;

  public static final String JSON_PROPERTY_EXTERNAL_TYPE_ID = "externalTypeId";
  private String externalTypeId;

  public static final String JSON_PROPERTY_TYPE_NAME = "typeName";
  private String typeName;

  public static final String JSON_PROPERTY_EXTERNAL_PRODUCT_ID = "externalProductId";
  private String externalProductId;

  public static final String JSON_PROPERTY_EXTERNAL_PRODUCT_KIND_ID = "externalProductKindId";
  private String externalProductKindId;

  public static final String JSON_PROPERTY_PRODUCT_KIND_NAME = "productKindName";
  private String productKindName;

  public static final String JSON_PROPERTY_EXTERNAL_PRODUCT_TYPE_ID = "externalProductTypeId";
  private String externalProductTypeId;

  public static final String JSON_PROPERTY_PRODUCT_TYPE_NAME = "productTypeName";
  private String productTypeName;

  public static final String JSON_PROPERTY_PRODUCT_KIND = "productKind";
  private ExternalProductKindItemExtended productKind;

  public static final String JSON_PROPERTY_TRANSLATIONS = "translations";
  private List<TranslationItem> translations = null;


  public AccountProductItem externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * A unique identifier for the product that the arrangement applies to 
   * @return externalId
  **/
  @javax.annotation.Nullable
 @Size(max=50)  @ApiModelProperty(value = "A unique identifier for the product that the arrangement applies to ")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public AccountProductItem externalTypeId(String externalTypeId) {
    
    this.externalTypeId = externalTypeId;
    return this;
  }

   /**
   * The ID that is used by the Bank to identify the specific Product type - External reference to the product Type.
   * @return externalTypeId
  **/
  @javax.annotation.Nullable
 @Size(max=50)  @ApiModelProperty(value = "The ID that is used by the Bank to identify the specific Product type - External reference to the product Type.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalTypeId() {
    return externalTypeId;
  }


  public void setExternalTypeId(String externalTypeId) {
    this.externalTypeId = externalTypeId;
  }


  public AccountProductItem typeName(String typeName) {
    
    this.typeName = typeName;
    return this;
  }

   /**
   * The label/name that is used to label a specific product type.
   * @return typeName
  **/
  @javax.annotation.Nullable
 @Size(max=50)  @ApiModelProperty(value = "The label/name that is used to label a specific product type.")
  @JsonProperty(JSON_PROPERTY_TYPE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTypeName() {
    return typeName;
  }


  public void setTypeName(String typeName) {
    this.typeName = typeName;
  }


  public AccountProductItem externalProductId(String externalProductId) {
    
    this.externalProductId = externalProductId;
    return this;
  }

   /**
   * A unique identifier for the product
   * @return externalProductId
  **/
  @NotNull
 @Size(min=1,max=50)  @ApiModelProperty(required = true, value = "A unique identifier for the product")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalProductId() {
    return externalProductId;
  }


  public void setExternalProductId(String externalProductId) {
    this.externalProductId = externalProductId;
  }


  public AccountProductItem externalProductKindId(String externalProductKindId) {
    
    this.externalProductKindId = externalProductKindId;
    return this;
  }

   /**
   * The ID that is internally used to uniquely identify the kind of product
   * @return externalProductKindId
  **/
  @NotNull
 @Size(min=1,max=50)  @ApiModelProperty(required = true, value = "The ID that is internally used to uniquely identify the kind of product")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_PRODUCT_KIND_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalProductKindId() {
    return externalProductKindId;
  }


  public void setExternalProductKindId(String externalProductKindId) {
    this.externalProductKindId = externalProductKindId;
  }


  public AccountProductItem productKindName(String productKindName) {
    
    this.productKindName = productKindName;
    return this;
  }

   /**
   * The label that is used for the respective product kind
   * @return productKindName
  **/
  @javax.annotation.Nullable
 @Size(min=1,max=50)  @ApiModelProperty(value = "The label that is used for the respective product kind")
  @JsonProperty(JSON_PROPERTY_PRODUCT_KIND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductKindName() {
    return productKindName;
  }


  public void setProductKindName(String productKindName) {
    this.productKindName = productKindName;
  }


  public AccountProductItem externalProductTypeId(String externalProductTypeId) {
    
    this.externalProductTypeId = externalProductTypeId;
    return this;
  }

   /**
   * The ID that is used by the Bank to identify the Product
   * @return externalProductTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID that is used by the Bank to identify the Product")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_PRODUCT_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalProductTypeId() {
    return externalProductTypeId;
  }


  public void setExternalProductTypeId(String externalProductTypeId) {
    this.externalProductTypeId = externalProductTypeId;
  }


  public AccountProductItem productTypeName(String productTypeName) {
    
    this.productTypeName = productTypeName;
    return this;
  }

   /**
   * The name that is used by the bank to label a specific product type
   * @return productTypeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name that is used by the bank to label a specific product type")
  @JsonProperty(JSON_PROPERTY_PRODUCT_TYPE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductTypeName() {
    return productTypeName;
  }


  public void setProductTypeName(String productTypeName) {
    this.productTypeName = productTypeName;
  }


  public AccountProductItem productKind(ExternalProductKindItemExtended productKind) {
    
    this.productKind = productKind;
    return this;
  }

   /**
   * Get productKind
   * @return productKind
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ExternalProductKindItemExtended getProductKind() {
    return productKind;
  }


  public void setProductKind(ExternalProductKindItemExtended productKind) {
    this.productKind = productKind;
  }


  public AccountProductItem translations(List<TranslationItem> translations) {
    
    this.translations = translations;
    return this;
  }

  public AccountProductItem addTranslationsItem(TranslationItem translationsItem) {
    if (this.translations == null) {
      this.translations = new ArrayList<>();
    }
    this.translations.add(translationsItem);
    return this;
  }

   /**
   * Get translations
   * @return translations
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRANSLATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TranslationItem> getTranslations() {
    return translations;
  }


  public void setTranslations(List<TranslationItem> translations) {
    this.translations = translations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountProductItem accountProductItem = (AccountProductItem) o;
    return Objects.equals(this.externalId, accountProductItem.externalId) &&
        Objects.equals(this.externalTypeId, accountProductItem.externalTypeId) &&
        Objects.equals(this.typeName, accountProductItem.typeName) &&
        Objects.equals(this.externalProductId, accountProductItem.externalProductId) &&
        Objects.equals(this.externalProductKindId, accountProductItem.externalProductKindId) &&
        Objects.equals(this.productKindName, accountProductItem.productKindName) &&
        Objects.equals(this.externalProductTypeId, accountProductItem.externalProductTypeId) &&
        Objects.equals(this.productTypeName, accountProductItem.productTypeName) &&
        Objects.equals(this.productKind, accountProductItem.productKind) &&
        Objects.equals(this.translations, accountProductItem.translations) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalId, externalTypeId, typeName, externalProductId, externalProductKindId, productKindName, externalProductTypeId, productTypeName, productKind, translations, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountProductItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    externalTypeId: ").append(toIndentedString(externalTypeId)).append("\n");
    sb.append("    typeName: ").append(toIndentedString(typeName)).append("\n");
    sb.append("    externalProductId: ").append(toIndentedString(externalProductId)).append("\n");
    sb.append("    externalProductKindId: ").append(toIndentedString(externalProductKindId)).append("\n");
    sb.append("    productKindName: ").append(toIndentedString(productKindName)).append("\n");
    sb.append("    externalProductTypeId: ").append(toIndentedString(externalProductTypeId)).append("\n");
    sb.append("    productTypeName: ").append(toIndentedString(productTypeName)).append("\n");
    sb.append("    productKind: ").append(toIndentedString(productKind)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

