/*
 * Arrangement Manager Service API
 * This API allows other DBS services to operate on products
 *
 * The version of the OpenAPI document: 2.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.arrangement.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.arrangement.service.api.listener.v2.model.AdditionalProperties;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Locale Translation item
 */
@ApiModel(description = "Locale Translation item")
@JsonPropertyOrder({
  LocaleTranslationItem.JSON_PROPERTY_FIELD_NAME,
  LocaleTranslationItem.JSON_PROPERTY_FIELD_VALUE
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:30:51.050595100+01:00[Africa/Tunis]")
public  class LocaleTranslationItem extends AdditionalProperties {
  public static final String JSON_PROPERTY_FIELD_NAME = "fieldName";
  private String fieldName;

  public static final String JSON_PROPERTY_FIELD_VALUE = "fieldValue";
  private String fieldValue;


  public LocaleTranslationItem fieldName(String fieldName) {
    
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Defines the name of the field that is translated.
   * @return fieldName
  **/
  @NotNull
 @Size(min=1,max=50)  @ApiModelProperty(required = true, value = "Defines the name of the field that is translated.")
  @JsonProperty(JSON_PROPERTY_FIELD_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFieldName() {
    return fieldName;
  }


  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }


  public LocaleTranslationItem fieldValue(String fieldValue) {
    
    this.fieldValue = fieldValue;
    return this;
  }

   /**
   * Defines the translated value of the field.
   * @return fieldValue
  **/
  @NotNull
 @Size(min=1,max=50)  @ApiModelProperty(required = true, value = "Defines the translated value of the field.")
  @JsonProperty(JSON_PROPERTY_FIELD_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFieldValue() {
    return fieldValue;
  }


  public void setFieldValue(String fieldValue) {
    this.fieldValue = fieldValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocaleTranslationItem localeTranslationItem = (LocaleTranslationItem) o;
    return Objects.equals(this.fieldName, localeTranslationItem.fieldName) &&
        Objects.equals(this.fieldValue, localeTranslationItem.fieldValue) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldName, fieldValue, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocaleTranslationItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    fieldValue: ").append(toIndentedString(fieldValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

