/*
 * Legal Entity Name client API
 * OpenApi Endpoints for managing Legal Entities Ancestors. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.onboarding.client.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * LegalEntityPostRequest
 */
@JsonPropertyOrder({
  LegalEntityPostRequest.JSON_PROPERTY_EXTERNAL_ID,
  LegalEntityPostRequest.JSON_PROPERTY_NAME,
  LegalEntityPostRequest.JSON_PROPERTY_OFFER,
  LegalEntityPostRequest.JSON_PROPERTY_SUBSCRIPTION_TYPE,
  LegalEntityPostRequest.JSON_PROPERTY_BILLING_ACCOUNT,
  LegalEntityPostRequest.JSON_PROPERTY_EMAIL,
  LegalEntityPostRequest.JSON_PROPERTY_CARDS_EXTERNAL_IDS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:54.559235200+01:00[Africa/Tunis]")
public  class LegalEntityPostRequest {
  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private String externalId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_OFFER = "offer";
  private String offer;

  public static final String JSON_PROPERTY_SUBSCRIPTION_TYPE = "subscriptionType";
  private String subscriptionType;

  public static final String JSON_PROPERTY_BILLING_ACCOUNT = "billingAccount";
  private String billingAccount;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_CARDS_EXTERNAL_IDS = "cardsExternalIds";
  private List<String> cardsExternalIds = new ArrayList<>();


  public LegalEntityPostRequest externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public LegalEntityPostRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public LegalEntityPostRequest offer(String offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_OFFER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOffer() {
    return offer;
  }


  public void setOffer(String offer) {
    this.offer = offer;
  }


  public LegalEntityPostRequest subscriptionType(String subscriptionType) {
    
    this.subscriptionType = subscriptionType;
    return this;
  }

   /**
   * Get subscriptionType
   * @return subscriptionType
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSubscriptionType() {
    return subscriptionType;
  }


  public void setSubscriptionType(String subscriptionType) {
    this.subscriptionType = subscriptionType;
  }


  public LegalEntityPostRequest billingAccount(String billingAccount) {
    
    this.billingAccount = billingAccount;
    return this;
  }

   /**
   * Get billingAccount
   * @return billingAccount
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BILLING_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBillingAccount() {
    return billingAccount;
  }


  public void setBillingAccount(String billingAccount) {
    this.billingAccount = billingAccount;
  }


  public LegalEntityPostRequest email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public LegalEntityPostRequest cardsExternalIds(List<String> cardsExternalIds) {
    
    this.cardsExternalIds = cardsExternalIds;
    return this;
  }

  public LegalEntityPostRequest addCardsExternalIdsItem(String cardsExternalIdsItem) {
    this.cardsExternalIds.add(cardsExternalIdsItem);
    return this;
  }

   /**
   * Get cardsExternalIds
   * @return cardsExternalIds
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CARDS_EXTERNAL_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getCardsExternalIds() {
    return cardsExternalIds;
  }


  public void setCardsExternalIds(List<String> cardsExternalIds) {
    this.cardsExternalIds = cardsExternalIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalEntityPostRequest legalEntityPostRequest = (LegalEntityPostRequest) o;
    return Objects.equals(this.externalId, legalEntityPostRequest.externalId) &&
        Objects.equals(this.name, legalEntityPostRequest.name) &&
        Objects.equals(this.offer, legalEntityPostRequest.offer) &&
        Objects.equals(this.subscriptionType, legalEntityPostRequest.subscriptionType) &&
        Objects.equals(this.billingAccount, legalEntityPostRequest.billingAccount) &&
        Objects.equals(this.email, legalEntityPostRequest.email) &&
        Objects.equals(this.cardsExternalIds, legalEntityPostRequest.cardsExternalIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalId, name, offer, subscriptionType, billingAccount, email, cardsExternalIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalEntityPostRequest {\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("    subscriptionType: ").append(toIndentedString(subscriptionType)).append("\n");
    sb.append("    billingAccount: ").append(toIndentedString(billingAccount)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    cardsExternalIds: ").append(toIndentedString(cardsExternalIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

