/*
 * Legal Entity Name client API
 * OpenApi Endpoints for managing Legal Entities Ancestors. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.onboarding.client.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * SubscriptionResponseBodyCards
 */
@JsonPropertyOrder({
  SubscriptionResponseBodyCards.JSON_PROPERTY_EXTERNAL_ID,
  SubscriptionResponseBodyCards.JSON_PROPERTY_NAME_EN,
  SubscriptionResponseBodyCards.JSON_PROPERTY_NAME_FR
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:54.559235200+01:00[Africa/Tunis]")
public  class SubscriptionResponseBodyCards {
  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private String externalId;

  public static final String JSON_PROPERTY_NAME_EN = "nameEn";
  private String nameEn;

  public static final String JSON_PROPERTY_NAME_FR = "nameFr";
  private String nameFr;


  public SubscriptionResponseBodyCards externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public SubscriptionResponseBodyCards nameEn(String nameEn) {
    
    this.nameEn = nameEn;
    return this;
  }

   /**
   * Get nameEn
   * @return nameEn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameEn() {
    return nameEn;
  }


  public void setNameEn(String nameEn) {
    this.nameEn = nameEn;
  }


  public SubscriptionResponseBodyCards nameFr(String nameFr) {
    
    this.nameFr = nameFr;
    return this;
  }

   /**
   * Get nameFr
   * @return nameFr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_FR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameFr() {
    return nameFr;
  }


  public void setNameFr(String nameFr) {
    this.nameFr = nameFr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionResponseBodyCards subscriptionResponseBodyCards = (SubscriptionResponseBodyCards) o;
    return Objects.equals(this.externalId, subscriptionResponseBodyCards.externalId) &&
        Objects.equals(this.nameEn, subscriptionResponseBodyCards.nameEn) &&
        Objects.equals(this.nameFr, subscriptionResponseBodyCards.nameFr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalId, nameEn, nameFr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionResponseBodyCards {\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    nameFr: ").append(toIndentedString(nameFr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

