/*
 * Legal Entity Name client API
 * OpenApi Endpoints for managing Legal Entities Ancestors. 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.onboarding.client.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.onboarding.client.api.listener.v2.model.SubscriptionResponseBodyCards;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * SubscriptionResponseBody
 */
@JsonPropertyOrder({
  SubscriptionResponseBody.JSON_PROPERTY_SUBSCRIPTION_ID,
  SubscriptionResponseBody.JSON_PROPERTY_LEGAL_ENTITY_NAME,
  SubscriptionResponseBody.JSON_PROPERTY_LEGAL_ENTITY_EXT_ID,
  SubscriptionResponseBody.JSON_PROPERTY_OFFER,
  SubscriptionResponseBody.JSON_PROPERTY_STATUS,
  SubscriptionResponseBody.JSON_PROPERTY_ACCOUNT_PULLED,
  SubscriptionResponseBody.JSON_PROPERTY_ACCOUNT_GROUP_CREATED,
  SubscriptionResponseBody.JSON_PROPERTY_IBS_ACTIVATED,
  SubscriptionResponseBody.JSON_PROPERTY_SUBSCRIPTION_TYPE,
  SubscriptionResponseBody.JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_ID,
  SubscriptionResponseBody.JSON_PROPERTY_BILLING_ACCOUNT,
  SubscriptionResponseBody.JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_STATUS,
  SubscriptionResponseBody.JSON_PROPERTY_SUBSCRIPTION_STATUS,
  SubscriptionResponseBody.JSON_PROPERTY_EMAIL,
  SubscriptionResponseBody.JSON_PROPERTY_CARDS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:54.559235200+01:00[Africa/Tunis]")
public  class SubscriptionResponseBody {
  public static final String JSON_PROPERTY_SUBSCRIPTION_ID = "subscriptionId";
  private String subscriptionId;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_NAME = "legalEntityName";
  private String legalEntityName;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_EXT_ID = "legalEntityExtId";
  private String legalEntityExtId;

  public static final String JSON_PROPERTY_OFFER = "offer";
  private String offer;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_ACCOUNT_PULLED = "accountPulled";
  private String accountPulled;

  public static final String JSON_PROPERTY_ACCOUNT_GROUP_CREATED = "accountGroupCreated";
  private String accountGroupCreated;

  public static final String JSON_PROPERTY_IBS_ACTIVATED = "ibsActivated";
  private String ibsActivated;

  public static final String JSON_PROPERTY_SUBSCRIPTION_TYPE = "subscriptionType";
  private String subscriptionType;

  public static final String JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_ID = "externalSubscriptionId";
  private String externalSubscriptionId;

  public static final String JSON_PROPERTY_BILLING_ACCOUNT = "billingAccount";
  private String billingAccount;

  public static final String JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_STATUS = "externalSubscriptionStatus";
  private String externalSubscriptionStatus;

  /**
   * Gets or Sets subscriptionStatus
   */
  public enum SubscriptionStatusEnum {
    ACTIVE("ACTIVE"),
    
    RESCINDED("RESCINDED"),
    
    INACTIVE("INACTIVE"),
    
    ACTIVATION_LOADING("ACTIVATION_LOADING"),
    
    ACTIVATION_FAILED("ACTIVATION_FAILED");

    private String value;

    SubscriptionStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SubscriptionStatusEnum fromValue(String value) {
      for (SubscriptionStatusEnum b : SubscriptionStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SUBSCRIPTION_STATUS = "subscriptionStatus";
  private SubscriptionStatusEnum subscriptionStatus;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_CARDS = "cards";
  private List<SubscriptionResponseBodyCards> cards = null;


  public SubscriptionResponseBody subscriptionId(String subscriptionId) {
    
    this.subscriptionId = subscriptionId;
    return this;
  }

   /**
   * Get subscriptionId
   * @return subscriptionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubscriptionId() {
    return subscriptionId;
  }


  public void setSubscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }


  public SubscriptionResponseBody legalEntityName(String legalEntityName) {
    
    this.legalEntityName = legalEntityName;
    return this;
  }

   /**
   * Get legalEntityName
   * @return legalEntityName
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LEGAL_ENTITY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLegalEntityName() {
    return legalEntityName;
  }


  public void setLegalEntityName(String legalEntityName) {
    this.legalEntityName = legalEntityName;
  }


  public SubscriptionResponseBody legalEntityExtId(String legalEntityExtId) {
    
    this.legalEntityExtId = legalEntityExtId;
    return this;
  }

   /**
   * Get legalEntityExtId
   * @return legalEntityExtId
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LEGAL_ENTITY_EXT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLegalEntityExtId() {
    return legalEntityExtId;
  }


  public void setLegalEntityExtId(String legalEntityExtId) {
    this.legalEntityExtId = legalEntityExtId;
  }


  public SubscriptionResponseBody offer(String offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_OFFER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOffer() {
    return offer;
  }


  public void setOffer(String offer) {
    this.offer = offer;
  }


  public SubscriptionResponseBody status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public SubscriptionResponseBody accountPulled(String accountPulled) {
    
    this.accountPulled = accountPulled;
    return this;
  }

   /**
   * Get accountPulled
   * @return accountPulled
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_PULLED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccountPulled() {
    return accountPulled;
  }


  public void setAccountPulled(String accountPulled) {
    this.accountPulled = accountPulled;
  }


  public SubscriptionResponseBody accountGroupCreated(String accountGroupCreated) {
    
    this.accountGroupCreated = accountGroupCreated;
    return this;
  }

   /**
   * Get accountGroupCreated
   * @return accountGroupCreated
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_GROUP_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccountGroupCreated() {
    return accountGroupCreated;
  }


  public void setAccountGroupCreated(String accountGroupCreated) {
    this.accountGroupCreated = accountGroupCreated;
  }


  public SubscriptionResponseBody ibsActivated(String ibsActivated) {
    
    this.ibsActivated = ibsActivated;
    return this;
  }

   /**
   * Get ibsActivated
   * @return ibsActivated
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IBS_ACTIVATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIbsActivated() {
    return ibsActivated;
  }


  public void setIbsActivated(String ibsActivated) {
    this.ibsActivated = ibsActivated;
  }


  public SubscriptionResponseBody subscriptionType(String subscriptionType) {
    
    this.subscriptionType = subscriptionType;
    return this;
  }

   /**
   * Get subscriptionType
   * @return subscriptionType
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSubscriptionType() {
    return subscriptionType;
  }


  public void setSubscriptionType(String subscriptionType) {
    this.subscriptionType = subscriptionType;
  }


  public SubscriptionResponseBody externalSubscriptionId(String externalSubscriptionId) {
    
    this.externalSubscriptionId = externalSubscriptionId;
    return this;
  }

   /**
   * Get externalSubscriptionId
   * @return externalSubscriptionId
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalSubscriptionId() {
    return externalSubscriptionId;
  }


  public void setExternalSubscriptionId(String externalSubscriptionId) {
    this.externalSubscriptionId = externalSubscriptionId;
  }


  public SubscriptionResponseBody billingAccount(String billingAccount) {
    
    this.billingAccount = billingAccount;
    return this;
  }

   /**
   * Get billingAccount
   * @return billingAccount
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BILLING_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBillingAccount() {
    return billingAccount;
  }


  public void setBillingAccount(String billingAccount) {
    this.billingAccount = billingAccount;
  }


  public SubscriptionResponseBody externalSubscriptionStatus(String externalSubscriptionStatus) {
    
    this.externalSubscriptionStatus = externalSubscriptionStatus;
    return this;
  }

   /**
   * Get externalSubscriptionStatus
   * @return externalSubscriptionStatus
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalSubscriptionStatus() {
    return externalSubscriptionStatus;
  }


  public void setExternalSubscriptionStatus(String externalSubscriptionStatus) {
    this.externalSubscriptionStatus = externalSubscriptionStatus;
  }


  public SubscriptionResponseBody subscriptionStatus(SubscriptionStatusEnum subscriptionStatus) {
    
    this.subscriptionStatus = subscriptionStatus;
    return this;
  }

   /**
   * Get subscriptionStatus
   * @return subscriptionStatus
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SubscriptionStatusEnum getSubscriptionStatus() {
    return subscriptionStatus;
  }


  public void setSubscriptionStatus(SubscriptionStatusEnum subscriptionStatus) {
    this.subscriptionStatus = subscriptionStatus;
  }


  public SubscriptionResponseBody email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public SubscriptionResponseBody cards(List<SubscriptionResponseBodyCards> cards) {
    
    this.cards = cards;
    return this;
  }

  public SubscriptionResponseBody addCardsItem(SubscriptionResponseBodyCards cardsItem) {
    if (this.cards == null) {
      this.cards = new ArrayList<>();
    }
    this.cards.add(cardsItem);
    return this;
  }

   /**
   * Get cards
   * @return cards
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SubscriptionResponseBodyCards> getCards() {
    return cards;
  }


  public void setCards(List<SubscriptionResponseBodyCards> cards) {
    this.cards = cards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionResponseBody subscriptionResponseBody = (SubscriptionResponseBody) o;
    return Objects.equals(this.subscriptionId, subscriptionResponseBody.subscriptionId) &&
        Objects.equals(this.legalEntityName, subscriptionResponseBody.legalEntityName) &&
        Objects.equals(this.legalEntityExtId, subscriptionResponseBody.legalEntityExtId) &&
        Objects.equals(this.offer, subscriptionResponseBody.offer) &&
        Objects.equals(this.status, subscriptionResponseBody.status) &&
        Objects.equals(this.accountPulled, subscriptionResponseBody.accountPulled) &&
        Objects.equals(this.accountGroupCreated, subscriptionResponseBody.accountGroupCreated) &&
        Objects.equals(this.ibsActivated, subscriptionResponseBody.ibsActivated) &&
        Objects.equals(this.subscriptionType, subscriptionResponseBody.subscriptionType) &&
        Objects.equals(this.externalSubscriptionId, subscriptionResponseBody.externalSubscriptionId) &&
        Objects.equals(this.billingAccount, subscriptionResponseBody.billingAccount) &&
        Objects.equals(this.externalSubscriptionStatus, subscriptionResponseBody.externalSubscriptionStatus) &&
        Objects.equals(this.subscriptionStatus, subscriptionResponseBody.subscriptionStatus) &&
        Objects.equals(this.email, subscriptionResponseBody.email) &&
        Objects.equals(this.cards, subscriptionResponseBody.cards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscriptionId, legalEntityName, legalEntityExtId, offer, status, accountPulled, accountGroupCreated, ibsActivated, subscriptionType, externalSubscriptionId, billingAccount, externalSubscriptionStatus, subscriptionStatus, email, cards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionResponseBody {\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    legalEntityName: ").append(toIndentedString(legalEntityName)).append("\n");
    sb.append("    legalEntityExtId: ").append(toIndentedString(legalEntityExtId)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    accountPulled: ").append(toIndentedString(accountPulled)).append("\n");
    sb.append("    accountGroupCreated: ").append(toIndentedString(accountGroupCreated)).append("\n");
    sb.append("    ibsActivated: ").append(toIndentedString(ibsActivated)).append("\n");
    sb.append("    subscriptionType: ").append(toIndentedString(subscriptionType)).append("\n");
    sb.append("    externalSubscriptionId: ").append(toIndentedString(externalSubscriptionId)).append("\n");
    sb.append("    billingAccount: ").append(toIndentedString(billingAccount)).append("\n");
    sb.append("    externalSubscriptionStatus: ").append(toIndentedString(externalSubscriptionStatus)).append("\n");
    sb.append("    subscriptionStatus: ").append(toIndentedString(subscriptionStatus)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    cards: ").append(toIndentedString(cards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

