/*
 * Approvals service
 * Other services approve or reject approvals, and update approval types, policies, and policy assignments.
 *
 * The version of the OpenAPI document: 2.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.approval.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.approval.service.api.listener.v2.model.PresentationPolicyAssignmentRequestBounds;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * This object describes the data group ids and related policy bounds infromation.
 */
@ApiModel(description = "This object describes the data group ids and related policy bounds infromation.")
@JsonPropertyOrder({
  PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds.JSON_PROPERTY_DATA_GROUP_IDS,
  PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds.JSON_PROPERTY_BOUNDS,
  PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds.JSON_PROPERTY_ADDITIONS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:49.266495+01:00[Africa/Tunis]")
public  class PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds {
  public static final String JSON_PROPERTY_DATA_GROUP_IDS = "dataGroupIds";
  private List<String> dataGroupIds = new ArrayList<>();

  public static final String JSON_PROPERTY_BOUNDS = "bounds";
  private List<PresentationPolicyAssignmentRequestBounds> bounds = new ArrayList<>();

  public static final String JSON_PROPERTY_ADDITIONS = "additions";
  private Map<String, String> additions = null;


  public PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds dataGroupIds(List<String> dataGroupIds) {
    
    this.dataGroupIds = dataGroupIds;
    return this;
  }

  public PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds addDataGroupIdsItem(String dataGroupIdsItem) {
    this.dataGroupIds.add(dataGroupIdsItem);
    return this;
  }

   /**
   * Get dataGroupIds
   * @return dataGroupIds
  **/
  @NotNull
 @Size(min=1,max=25)  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DATA_GROUP_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getDataGroupIds() {
    return dataGroupIds;
  }


  public void setDataGroupIds(List<String> dataGroupIds) {
    this.dataGroupIds = dataGroupIds;
  }


  public PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds bounds(List<PresentationPolicyAssignmentRequestBounds> bounds) {
    
    this.bounds = bounds;
    return this;
  }

  public PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds addBoundsItem(PresentationPolicyAssignmentRequestBounds boundsItem) {
    this.bounds.add(boundsItem);
    return this;
  }

   /**
   * Get bounds
   * @return bounds
  **/
  @NotNull
  @Valid
 @Size(min=1,max=50)  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_BOUNDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PresentationPolicyAssignmentRequestBounds> getBounds() {
    return bounds;
  }


  public void setBounds(List<PresentationPolicyAssignmentRequestBounds> bounds) {
    this.bounds = bounds;
  }


  public PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds additions(Map<String, String> additions) {
    
    this.additions = additions;
    return this;
  }

  public PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds putAdditionsItem(String key, String additionsItem) {
    if (this.additions == null) {
      this.additions = new HashMap<>();
    }
    this.additions.put(key, additionsItem);
    return this;
  }

   /**
   * Additional properties
   * @return additions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional properties")
  @JsonProperty(JSON_PROPERTY_ADDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getAdditions() {
    return additions;
  }


  public void setAdditions(Map<String, String> additions) {
    this.additions = additions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds presentationDataGroupSpecificPolicyAssignmentBulkRequestBounds = (PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds) o;
    return Objects.equals(this.dataGroupIds, presentationDataGroupSpecificPolicyAssignmentBulkRequestBounds.dataGroupIds) &&
        Objects.equals(this.bounds, presentationDataGroupSpecificPolicyAssignmentBulkRequestBounds.bounds) &&
        Objects.equals(this.additions, presentationDataGroupSpecificPolicyAssignmentBulkRequestBounds.additions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataGroupIds, bounds, additions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresentationDataGroupSpecificPolicyAssignmentBulkRequestBounds {\n");
    sb.append("    dataGroupIds: ").append(toIndentedString(dataGroupIds)).append("\n");
    sb.append("    bounds: ").append(toIndentedString(bounds)).append("\n");
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

