/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PersistencePrivilege;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * FunctionsGetResponseBodyAllOf
 */
@JsonPropertyOrder({
  FunctionsGetResponseBodyAllOf.JSON_PROPERTY_FUNCTION_ID,
  FunctionsGetResponseBodyAllOf.JSON_PROPERTY_FUNCTION_CODE,
  FunctionsGetResponseBodyAllOf.JSON_PROPERTY_RESOURCE,
  FunctionsGetResponseBodyAllOf.JSON_PROPERTY_RESOURCE_CODE,
  FunctionsGetResponseBodyAllOf.JSON_PROPERTY_NAME,
  FunctionsGetResponseBodyAllOf.JSON_PROPERTY_PRIVILEGES
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class FunctionsGetResponseBodyAllOf {
  public static final String JSON_PROPERTY_FUNCTION_ID = "functionId";
  private String functionId;

  public static final String JSON_PROPERTY_FUNCTION_CODE = "functionCode";
  private String functionCode;

  public static final String JSON_PROPERTY_RESOURCE = "resource";
  private String resource;

  public static final String JSON_PROPERTY_RESOURCE_CODE = "resourceCode";
  private String resourceCode;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PRIVILEGES = "privileges";
  private List<PersistencePrivilege> privileges = null;


  public FunctionsGetResponseBodyAllOf functionId(String functionId) {
    
    this.functionId = functionId;
    return this;
  }

   /**
   * Internal id of business function
   * @return functionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Internal id of business function")
  @JsonProperty(JSON_PROPERTY_FUNCTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunctionId() {
    return functionId;
  }


  public void setFunctionId(String functionId) {
    this.functionId = functionId;
  }


  public FunctionsGetResponseBodyAllOf functionCode(String functionCode) {
    
    this.functionCode = functionCode;
    return this;
  }

   /**
   * Code of business function
   * @return functionCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code of business function")
  @JsonProperty(JSON_PROPERTY_FUNCTION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunctionCode() {
    return functionCode;
  }


  public void setFunctionCode(String functionCode) {
    this.functionCode = functionCode;
  }


  public FunctionsGetResponseBodyAllOf resource(String resource) {
    
    this.resource = resource;
    return this;
  }

   /**
   * Name of resource
   * @return resource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of resource")
  @JsonProperty(JSON_PROPERTY_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResource() {
    return resource;
  }


  public void setResource(String resource) {
    this.resource = resource;
  }


  public FunctionsGetResponseBodyAllOf resourceCode(String resourceCode) {
    
    this.resourceCode = resourceCode;
    return this;
  }

   /**
   * Code of resource
   * @return resourceCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code of resource")
  @JsonProperty(JSON_PROPERTY_RESOURCE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResourceCode() {
    return resourceCode;
  }


  public void setResourceCode(String resourceCode) {
    this.resourceCode = resourceCode;
  }


  public FunctionsGetResponseBodyAllOf name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Business function name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Business function name")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public FunctionsGetResponseBodyAllOf privileges(List<PersistencePrivilege> privileges) {
    
    this.privileges = privileges;
    return this;
  }

  public FunctionsGetResponseBodyAllOf addPrivilegesItem(PersistencePrivilege privilegesItem) {
    if (this.privileges == null) {
      this.privileges = new ArrayList<>();
    }
    this.privileges.add(privilegesItem);
    return this;
  }

   /**
   * Applicable privileges for business function
   * @return privileges
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "Applicable privileges for business function")
  @JsonProperty(JSON_PROPERTY_PRIVILEGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PersistencePrivilege> getPrivileges() {
    return privileges;
  }


  public void setPrivileges(List<PersistencePrivilege> privileges) {
    this.privileges = privileges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionsGetResponseBodyAllOf functionsGetResponseBodyAllOf = (FunctionsGetResponseBodyAllOf) o;
    return Objects.equals(this.functionId, functionsGetResponseBodyAllOf.functionId) &&
        Objects.equals(this.functionCode, functionsGetResponseBodyAllOf.functionCode) &&
        Objects.equals(this.resource, functionsGetResponseBodyAllOf.resource) &&
        Objects.equals(this.resourceCode, functionsGetResponseBodyAllOf.resourceCode) &&
        Objects.equals(this.name, functionsGetResponseBodyAllOf.name) &&
        Objects.equals(this.privileges, functionsGetResponseBodyAllOf.privileges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functionId, functionCode, resource, resourceCode, name, privileges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionsGetResponseBodyAllOf {\n");
    sb.append("    functionId: ").append(toIndentedString(functionId)).append("\n");
    sb.append("    functionCode: ").append(toIndentedString(functionCode)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    resourceCode: ").append(toIndentedString(resourceCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    privileges: ").append(toIndentedString(privileges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

