/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.AdditionalPropertiesAware;
import com.microsphere.accesscontrol.service.api.listener.v2.model.GetServiceAgreementAllOf;
import com.microsphere.accesscontrol.service.api.listener.v2.model.Status;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * GetServiceAgreement
 */
@JsonPropertyOrder({
  GetServiceAgreement.JSON_PROPERTY_ADDITIONS,
  GetServiceAgreement.JSON_PROPERTY_ID,
  GetServiceAgreement.JSON_PROPERTY_EXTERNAL_ID,
  GetServiceAgreement.JSON_PROPERTY_NAME,
  GetServiceAgreement.JSON_PROPERTY_DESCRIPTION,
  GetServiceAgreement.JSON_PROPERTY_CREATOR_LEGAL_ENTITY,
  GetServiceAgreement.JSON_PROPERTY_IS_MASTER,
  GetServiceAgreement.JSON_PROPERTY_STATUS,
  GetServiceAgreement.JSON_PROPERTY_VALID_FROM_DATE,
  GetServiceAgreement.JSON_PROPERTY_VALID_FROM_TIME,
  GetServiceAgreement.JSON_PROPERTY_VALID_UNTIL_DATE,
  GetServiceAgreement.JSON_PROPERTY_VALID_UNTIL_TIME
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class GetServiceAgreement {
  public static final String JSON_PROPERTY_ADDITIONS = "additions";
  private Map<String, String> additions = null;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private String externalId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_CREATOR_LEGAL_ENTITY = "creatorLegalEntity";
  private String creatorLegalEntity;

  public static final String JSON_PROPERTY_IS_MASTER = "isMaster";
  private Boolean isMaster = false;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Status status;

  public static final String JSON_PROPERTY_VALID_FROM_DATE = "validFromDate";
  private String validFromDate;

  public static final String JSON_PROPERTY_VALID_FROM_TIME = "validFromTime";
  private String validFromTime;

  public static final String JSON_PROPERTY_VALID_UNTIL_DATE = "validUntilDate";
  private String validUntilDate;

  public static final String JSON_PROPERTY_VALID_UNTIL_TIME = "validUntilTime";
  private String validUntilTime;


  public GetServiceAgreement additions(Map<String, String> additions) {
    
    this.additions = additions;
    return this;
  }

  public GetServiceAgreement putAdditionsItem(String key, String additionsItem) {
    if (this.additions == null) {
      this.additions = new HashMap<>();
    }
    this.additions.put(key, additionsItem);
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getAdditions() {
    return additions;
  }


  public void setAdditions(Map<String, String> additions) {
    this.additions = additions;
  }


  public GetServiceAgreement id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return id
  **/
  @NotNull
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(required = true, value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public GetServiceAgreement externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * External legal entity identifier.
   * @return externalId
  **/
  @javax.annotation.Nullable
 @Pattern(regexp="^[^\\r\\n]{1,64}$") @Size(min=1,max=64)  @ApiModelProperty(value = "External legal entity identifier.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public GetServiceAgreement name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @NotNull
 @Size(min=1,max=128)  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public GetServiceAgreement description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @NotNull
 @Size(min=1,max=255)  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public GetServiceAgreement creatorLegalEntity(String creatorLegalEntity) {
    
    this.creatorLegalEntity = creatorLegalEntity;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return creatorLegalEntity
  **/
  @javax.annotation.Nullable
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_CREATOR_LEGAL_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatorLegalEntity() {
    return creatorLegalEntity;
  }


  public void setCreatorLegalEntity(String creatorLegalEntity) {
    this.creatorLegalEntity = creatorLegalEntity;
  }


  public GetServiceAgreement isMaster(Boolean isMaster) {
    
    this.isMaster = isMaster;
    return this;
  }

   /**
   * Get isMaster
   * @return isMaster
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IS_MASTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsMaster() {
    return isMaster;
  }


  public void setIsMaster(Boolean isMaster) {
    this.isMaster = isMaster;
  }


  public GetServiceAgreement status(Status status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Status getStatus() {
    return status;
  }


  public void setStatus(Status status) {
    this.status = status;
  }


  public GetServiceAgreement validFromDate(String validFromDate) {
    
    this.validFromDate = validFromDate;
    return this;
  }

   /**
   * Start date of the service agreement.
   * @return validFromDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Start date of the service agreement.")
  @JsonProperty(JSON_PROPERTY_VALID_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValidFromDate() {
    return validFromDate;
  }


  public void setValidFromDate(String validFromDate) {
    this.validFromDate = validFromDate;
  }


  public GetServiceAgreement validFromTime(String validFromTime) {
    
    this.validFromTime = validFromTime;
    return this;
  }

   /**
   * Start time of the service agreement.
   * @return validFromTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Start time of the service agreement.")
  @JsonProperty(JSON_PROPERTY_VALID_FROM_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValidFromTime() {
    return validFromTime;
  }


  public void setValidFromTime(String validFromTime) {
    this.validFromTime = validFromTime;
  }


  public GetServiceAgreement validUntilDate(String validUntilDate) {
    
    this.validUntilDate = validUntilDate;
    return this;
  }

   /**
   * End date of the service agreement.
   * @return validUntilDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "End date of the service agreement.")
  @JsonProperty(JSON_PROPERTY_VALID_UNTIL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValidUntilDate() {
    return validUntilDate;
  }


  public void setValidUntilDate(String validUntilDate) {
    this.validUntilDate = validUntilDate;
  }


  public GetServiceAgreement validUntilTime(String validUntilTime) {
    
    this.validUntilTime = validUntilTime;
    return this;
  }

   /**
   * End time of the service agreement.
   * @return validUntilTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "End time of the service agreement.")
  @JsonProperty(JSON_PROPERTY_VALID_UNTIL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValidUntilTime() {
    return validUntilTime;
  }


  public void setValidUntilTime(String validUntilTime) {
    this.validUntilTime = validUntilTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetServiceAgreement getServiceAgreement = (GetServiceAgreement) o;
    return Objects.equals(this.additions, getServiceAgreement.additions) &&
        Objects.equals(this.id, getServiceAgreement.id) &&
        Objects.equals(this.externalId, getServiceAgreement.externalId) &&
        Objects.equals(this.name, getServiceAgreement.name) &&
        Objects.equals(this.description, getServiceAgreement.description) &&
        Objects.equals(this.creatorLegalEntity, getServiceAgreement.creatorLegalEntity) &&
        Objects.equals(this.isMaster, getServiceAgreement.isMaster) &&
        Objects.equals(this.status, getServiceAgreement.status) &&
        Objects.equals(this.validFromDate, getServiceAgreement.validFromDate) &&
        Objects.equals(this.validFromTime, getServiceAgreement.validFromTime) &&
        Objects.equals(this.validUntilDate, getServiceAgreement.validUntilDate) &&
        Objects.equals(this.validUntilTime, getServiceAgreement.validUntilTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additions, id, externalId, name, description, creatorLegalEntity, isMaster, status, validFromDate, validFromTime, validUntilDate, validUntilTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetServiceAgreement {\n");
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    creatorLegalEntity: ").append(toIndentedString(creatorLegalEntity)).append("\n");
    sb.append("    isMaster: ").append(toIndentedString(isMaster)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    validFromDate: ").append(toIndentedString(validFromDate)).append("\n");
    sb.append("    validFromTime: ").append(toIndentedString(validFromTime)).append("\n");
    sb.append("    validUntilDate: ").append(toIndentedString(validUntilDate)).append("\n");
    sb.append("    validUntilTime: ").append(toIndentedString(validUntilTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

