/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.AdditionalPropertiesAware;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PresentationPermissionItem;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PresentationPermissionSetResponseItemAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * PresentationPermissionSetResponseItem
 */
@JsonPropertyOrder({
  PresentationPermissionSetResponseItem.JSON_PROPERTY_ADDITIONS,
  PresentationPermissionSetResponseItem.JSON_PROPERTY_ID,
  PresentationPermissionSetResponseItem.JSON_PROPERTY_NAME,
  PresentationPermissionSetResponseItem.JSON_PROPERTY_DESCRIPTION,
  PresentationPermissionSetResponseItem.JSON_PROPERTY_TYPE,
  PresentationPermissionSetResponseItem.JSON_PROPERTY_PERMISSIONS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class PresentationPermissionSetResponseItem {
  public static final String JSON_PROPERTY_ADDITIONS = "additions";
  private Map<String, String> additions = null;

  public static final String JSON_PROPERTY_ID = "id";
  private BigDecimal id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  private List<PresentationPermissionItem> permissions = null;


  public PresentationPermissionSetResponseItem additions(Map<String, String> additions) {
    
    this.additions = additions;
    return this;
  }

  public PresentationPermissionSetResponseItem putAdditionsItem(String key, String additionsItem) {
    if (this.additions == null) {
      this.additions = new HashMap<>();
    }
    this.additions.put(key, additionsItem);
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getAdditions() {
    return additions;
  }


  public void setAdditions(Map<String, String> additions) {
    this.additions = additions;
  }


  public PresentationPermissionSetResponseItem id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * Internal id of the assignable permission set.
   * @return id
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "Internal id of the assignable permission set.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public PresentationPermissionSetResponseItem name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the assignable permission set.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the assignable permission set.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public PresentationPermissionSetResponseItem description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of the assignable permission set.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the assignable permission set.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PresentationPermissionSetResponseItem type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of the assignable permission set.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of the assignable permission set.")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public PresentationPermissionSetResponseItem permissions(List<PresentationPermissionItem> permissions) {
    
    this.permissions = permissions;
    return this;
  }

  public PresentationPermissionSetResponseItem addPermissionsItem(PresentationPermissionItem permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Assignable permissions.
   * @return permissions
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "Assignable permissions.")
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PresentationPermissionItem> getPermissions() {
    return permissions;
  }


  public void setPermissions(List<PresentationPermissionItem> permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresentationPermissionSetResponseItem presentationPermissionSetResponseItem = (PresentationPermissionSetResponseItem) o;
    return Objects.equals(this.additions, presentationPermissionSetResponseItem.additions) &&
        Objects.equals(this.id, presentationPermissionSetResponseItem.id) &&
        Objects.equals(this.name, presentationPermissionSetResponseItem.name) &&
        Objects.equals(this.description, presentationPermissionSetResponseItem.description) &&
        Objects.equals(this.type, presentationPermissionSetResponseItem.type) &&
        Objects.equals(this.permissions, presentationPermissionSetResponseItem.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additions, id, name, description, type, permissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresentationPermissionSetResponseItem {\n");
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

