/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PresentationAction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Add Participants in Service Agreement
 */
@ApiModel(description = "Add Participants in Service Agreement")
@JsonPropertyOrder({
  PresentationParticipantPutBody.JSON_PROPERTY_ACTION,
  PresentationParticipantPutBody.JSON_PROPERTY_EXTERNAL_SERVICE_AGREEMENT_ID,
  PresentationParticipantPutBody.JSON_PROPERTY_EXTERNAL_PARTICIPANT_ID,
  PresentationParticipantPutBody.JSON_PROPERTY_SHARING_USERS,
  PresentationParticipantPutBody.JSON_PROPERTY_SHARING_ACCOUNTS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class PresentationParticipantPutBody {
  public static final String JSON_PROPERTY_ACTION = "action";
  private PresentationAction action;

  public static final String JSON_PROPERTY_EXTERNAL_SERVICE_AGREEMENT_ID = "externalServiceAgreementId";
  private String externalServiceAgreementId;

  public static final String JSON_PROPERTY_EXTERNAL_PARTICIPANT_ID = "externalParticipantId";
  private String externalParticipantId;

  public static final String JSON_PROPERTY_SHARING_USERS = "sharingUsers";
  private Boolean sharingUsers;

  public static final String JSON_PROPERTY_SHARING_ACCOUNTS = "sharingAccounts";
  private Boolean sharingAccounts;


  public PresentationParticipantPutBody action(PresentationAction action) {
    
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PresentationAction getAction() {
    return action;
  }


  public void setAction(PresentationAction action) {
    this.action = action;
  }


  public PresentationParticipantPutBody externalServiceAgreementId(String externalServiceAgreementId) {
    
    this.externalServiceAgreementId = externalServiceAgreementId;
    return this;
  }

   /**
   * External Unique Identifier.
   * @return externalServiceAgreementId
  **/
  @NotNull
 @Pattern(regexp="^[^\\r\\n]{1,64}$") @Size(min=1,max=64)  @ApiModelProperty(required = true, value = "External Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_SERVICE_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalServiceAgreementId() {
    return externalServiceAgreementId;
  }


  public void setExternalServiceAgreementId(String externalServiceAgreementId) {
    this.externalServiceAgreementId = externalServiceAgreementId;
  }


  public PresentationParticipantPutBody externalParticipantId(String externalParticipantId) {
    
    this.externalParticipantId = externalParticipantId;
    return this;
  }

   /**
   * External Unique Identifier.
   * @return externalParticipantId
  **/
  @NotNull
 @Pattern(regexp="^[^\\r\\n]{1,64}$") @Size(min=1,max=64)  @ApiModelProperty(required = true, value = "External Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_PARTICIPANT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalParticipantId() {
    return externalParticipantId;
  }


  public void setExternalParticipantId(String externalParticipantId) {
    this.externalParticipantId = externalParticipantId;
  }


  public PresentationParticipantPutBody sharingUsers(Boolean sharingUsers) {
    
    this.sharingUsers = sharingUsers;
    return this;
  }

   /**
   * Boolean value if the Participant is sharing users
   * @return sharingUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Boolean value if the Participant is sharing users")
  @JsonProperty(JSON_PROPERTY_SHARING_USERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSharingUsers() {
    return sharingUsers;
  }


  public void setSharingUsers(Boolean sharingUsers) {
    this.sharingUsers = sharingUsers;
  }


  public PresentationParticipantPutBody sharingAccounts(Boolean sharingAccounts) {
    
    this.sharingAccounts = sharingAccounts;
    return this;
  }

   /**
   * Boolean value if the Participant is sharing accounts
   * @return sharingAccounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Boolean value if the Participant is sharing accounts")
  @JsonProperty(JSON_PROPERTY_SHARING_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSharingAccounts() {
    return sharingAccounts;
  }


  public void setSharingAccounts(Boolean sharingAccounts) {
    this.sharingAccounts = sharingAccounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresentationParticipantPutBody presentationParticipantPutBody = (PresentationParticipantPutBody) o;
    return Objects.equals(this.action, presentationParticipantPutBody.action) &&
        Objects.equals(this.externalServiceAgreementId, presentationParticipantPutBody.externalServiceAgreementId) &&
        Objects.equals(this.externalParticipantId, presentationParticipantPutBody.externalParticipantId) &&
        Objects.equals(this.sharingUsers, presentationParticipantPutBody.sharingUsers) &&
        Objects.equals(this.sharingAccounts, presentationParticipantPutBody.sharingAccounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, externalServiceAgreementId, externalParticipantId, sharingUsers, sharingAccounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresentationParticipantPutBody {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    externalServiceAgreementId: ").append(toIndentedString(externalServiceAgreementId)).append("\n");
    sb.append("    externalParticipantId: ").append(toIndentedString(externalParticipantId)).append("\n");
    sb.append("    sharingUsers: ").append(toIndentedString(sharingUsers)).append("\n");
    sb.append("    sharingAccounts: ").append(toIndentedString(sharingAccounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

