/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PresentationUserApsIdentifiers;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * PresentationPermissionSetPut
 */
@JsonPropertyOrder({
  PresentationPermissionSetPut.JSON_PROPERTY_EXTERNAL_SERVICE_AGREEMENT_ID,
  PresentationPermissionSetPut.JSON_PROPERTY_REGULAR_USER_APS,
  PresentationPermissionSetPut.JSON_PROPERTY_ADMIN_USER_APS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class PresentationPermissionSetPut {
  public static final String JSON_PROPERTY_EXTERNAL_SERVICE_AGREEMENT_ID = "externalServiceAgreementId";
  private String externalServiceAgreementId;

  public static final String JSON_PROPERTY_REGULAR_USER_APS = "regularUserAps";
  private PresentationUserApsIdentifiers regularUserAps;

  public static final String JSON_PROPERTY_ADMIN_USER_APS = "adminUserAps";
  private PresentationUserApsIdentifiers adminUserAps;


  public PresentationPermissionSetPut externalServiceAgreementId(String externalServiceAgreementId) {
    
    this.externalServiceAgreementId = externalServiceAgreementId;
    return this;
  }

   /**
   * External service agreement id.
   * @return externalServiceAgreementId
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "External service agreement id.")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_SERVICE_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalServiceAgreementId() {
    return externalServiceAgreementId;
  }


  public void setExternalServiceAgreementId(String externalServiceAgreementId) {
    this.externalServiceAgreementId = externalServiceAgreementId;
  }


  public PresentationPermissionSetPut regularUserAps(PresentationUserApsIdentifiers regularUserAps) {
    
    this.regularUserAps = regularUserAps;
    return this;
  }

   /**
   * Get regularUserAps
   * @return regularUserAps
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REGULAR_USER_APS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PresentationUserApsIdentifiers getRegularUserAps() {
    return regularUserAps;
  }


  public void setRegularUserAps(PresentationUserApsIdentifiers regularUserAps) {
    this.regularUserAps = regularUserAps;
  }


  public PresentationPermissionSetPut adminUserAps(PresentationUserApsIdentifiers adminUserAps) {
    
    this.adminUserAps = adminUserAps;
    return this;
  }

   /**
   * Get adminUserAps
   * @return adminUserAps
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADMIN_USER_APS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PresentationUserApsIdentifiers getAdminUserAps() {
    return adminUserAps;
  }


  public void setAdminUserAps(PresentationUserApsIdentifiers adminUserAps) {
    this.adminUserAps = adminUserAps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresentationPermissionSetPut presentationPermissionSetPut = (PresentationPermissionSetPut) o;
    return Objects.equals(this.externalServiceAgreementId, presentationPermissionSetPut.externalServiceAgreementId) &&
        Objects.equals(this.regularUserAps, presentationPermissionSetPut.regularUserAps) &&
        Objects.equals(this.adminUserAps, presentationPermissionSetPut.adminUserAps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalServiceAgreementId, regularUserAps, adminUserAps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresentationPermissionSetPut {\n");
    sb.append("    externalServiceAgreementId: ").append(toIndentedString(externalServiceAgreementId)).append("\n");
    sb.append("    regularUserAps: ").append(toIndentedString(regularUserAps)).append("\n");
    sb.append("    adminUserAps: ").append(toIndentedString(adminUserAps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

