/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.LegalEntityIdentifier;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PresentationItemIdentifier;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PresentationServiceAgreementIdentifier;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * PresentationSearchDataGroupsRequest
 */
@JsonPropertyOrder({
  PresentationSearchDataGroupsRequest.JSON_PROPERTY_SERVICE_AGREEMENT_IDENTIFIER,
  PresentationSearchDataGroupsRequest.JSON_PROPERTY_DATA_ITEM_IDENTIFIER,
  PresentationSearchDataGroupsRequest.JSON_PROPERTY_LEGAL_ENTITY_IDENTIFIER
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class PresentationSearchDataGroupsRequest {
  public static final String JSON_PROPERTY_SERVICE_AGREEMENT_IDENTIFIER = "serviceAgreementIdentifier";
  private PresentationServiceAgreementIdentifier serviceAgreementIdentifier;

  public static final String JSON_PROPERTY_DATA_ITEM_IDENTIFIER = "dataItemIdentifier";
  private PresentationItemIdentifier dataItemIdentifier;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_IDENTIFIER = "legalEntityIdentifier";
  private LegalEntityIdentifier legalEntityIdentifier;


  public PresentationSearchDataGroupsRequest serviceAgreementIdentifier(PresentationServiceAgreementIdentifier serviceAgreementIdentifier) {
    
    this.serviceAgreementIdentifier = serviceAgreementIdentifier;
    return this;
  }

   /**
   * Get serviceAgreementIdentifier
   * @return serviceAgreementIdentifier
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVICE_AGREEMENT_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PresentationServiceAgreementIdentifier getServiceAgreementIdentifier() {
    return serviceAgreementIdentifier;
  }


  public void setServiceAgreementIdentifier(PresentationServiceAgreementIdentifier serviceAgreementIdentifier) {
    this.serviceAgreementIdentifier = serviceAgreementIdentifier;
  }


  public PresentationSearchDataGroupsRequest dataItemIdentifier(PresentationItemIdentifier dataItemIdentifier) {
    
    this.dataItemIdentifier = dataItemIdentifier;
    return this;
  }

   /**
   * Get dataItemIdentifier
   * @return dataItemIdentifier
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATA_ITEM_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PresentationItemIdentifier getDataItemIdentifier() {
    return dataItemIdentifier;
  }


  public void setDataItemIdentifier(PresentationItemIdentifier dataItemIdentifier) {
    this.dataItemIdentifier = dataItemIdentifier;
  }


  public PresentationSearchDataGroupsRequest legalEntityIdentifier(LegalEntityIdentifier legalEntityIdentifier) {
    
    this.legalEntityIdentifier = legalEntityIdentifier;
    return this;
  }

   /**
   * Get legalEntityIdentifier
   * @return legalEntityIdentifier
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LEGAL_ENTITY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LegalEntityIdentifier getLegalEntityIdentifier() {
    return legalEntityIdentifier;
  }


  public void setLegalEntityIdentifier(LegalEntityIdentifier legalEntityIdentifier) {
    this.legalEntityIdentifier = legalEntityIdentifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresentationSearchDataGroupsRequest presentationSearchDataGroupsRequest = (PresentationSearchDataGroupsRequest) o;
    return Objects.equals(this.serviceAgreementIdentifier, presentationSearchDataGroupsRequest.serviceAgreementIdentifier) &&
        Objects.equals(this.dataItemIdentifier, presentationSearchDataGroupsRequest.dataItemIdentifier) &&
        Objects.equals(this.legalEntityIdentifier, presentationSearchDataGroupsRequest.legalEntityIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceAgreementIdentifier, dataItemIdentifier, legalEntityIdentifier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresentationSearchDataGroupsRequest {\n");
    sb.append("    serviceAgreementIdentifier: ").append(toIndentedString(serviceAgreementIdentifier)).append("\n");
    sb.append("    dataItemIdentifier: ").append(toIndentedString(dataItemIdentifier)).append("\n");
    sb.append("    legalEntityIdentifier: ").append(toIndentedString(legalEntityIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

