/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.PresentationGenericObjectId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * PresentationFunctionDataGroup
 */
@JsonPropertyOrder({
  PresentationFunctionDataGroup.JSON_PROPERTY_FUNCTION_GROUP_ID,
  PresentationFunctionDataGroup.JSON_PROPERTY_DATA_GROUP_IDS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class PresentationFunctionDataGroup {
  public static final String JSON_PROPERTY_FUNCTION_GROUP_ID = "functionGroupId";
  private String functionGroupId;

  public static final String JSON_PROPERTY_DATA_GROUP_IDS = "dataGroupIds";
  private List<PresentationGenericObjectId> dataGroupIds = new ArrayList<>();


  public PresentationFunctionDataGroup functionGroupId(String functionGroupId) {
    
    this.functionGroupId = functionGroupId;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return functionGroupId
  **/
  @NotNull
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(required = true, value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_FUNCTION_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFunctionGroupId() {
    return functionGroupId;
  }


  public void setFunctionGroupId(String functionGroupId) {
    this.functionGroupId = functionGroupId;
  }


  public PresentationFunctionDataGroup dataGroupIds(List<PresentationGenericObjectId> dataGroupIds) {
    
    this.dataGroupIds = dataGroupIds;
    return this;
  }

  public PresentationFunctionDataGroup addDataGroupIdsItem(PresentationGenericObjectId dataGroupIdsItem) {
    this.dataGroupIds.add(dataGroupIdsItem);
    return this;
  }

   /**
   * Get dataGroupIds
   * @return dataGroupIds
  **/
  @NotNull
  @Valid
 @Size(min=0)  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DATA_GROUP_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PresentationGenericObjectId> getDataGroupIds() {
    return dataGroupIds;
  }


  public void setDataGroupIds(List<PresentationGenericObjectId> dataGroupIds) {
    this.dataGroupIds = dataGroupIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresentationFunctionDataGroup presentationFunctionDataGroup = (PresentationFunctionDataGroup) o;
    return Objects.equals(this.functionGroupId, presentationFunctionDataGroup.functionGroupId) &&
        Objects.equals(this.dataGroupIds, presentationFunctionDataGroup.dataGroupIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functionGroupId, dataGroupIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresentationFunctionDataGroup {\n");
    sb.append("    functionGroupId: ").append(toIndentedString(functionGroupId)).append("\n");
    sb.append("    dataGroupIds: ").append(toIndentedString(dataGroupIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

