/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.AccessResourceType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * UserAccessLegalEntitiesAllOf
 */
@JsonPropertyOrder({
  UserAccessLegalEntitiesAllOf.JSON_PROPERTY_CONTEXT_SERVICE_AGREEMENT_ID,
  UserAccessLegalEntitiesAllOf.JSON_PROPERTY_USER_LEGAL_ENTITY_ID,
  UserAccessLegalEntitiesAllOf.JSON_PROPERTY_ACCESS_RESOURCE_TYPE
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class UserAccessLegalEntitiesAllOf {
  public static final String JSON_PROPERTY_CONTEXT_SERVICE_AGREEMENT_ID = "contextServiceAgreementId";
  private String contextServiceAgreementId;

  public static final String JSON_PROPERTY_USER_LEGAL_ENTITY_ID = "userLegalEntityId";
  private String userLegalEntityId;

  public static final String JSON_PROPERTY_ACCESS_RESOURCE_TYPE = "accessResourceType";
  private AccessResourceType accessResourceType;


  public UserAccessLegalEntitiesAllOf contextServiceAgreementId(String contextServiceAgreementId) {
    
    this.contextServiceAgreementId = contextServiceAgreementId;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return contextServiceAgreementId
  **/
  @javax.annotation.Nullable
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_CONTEXT_SERVICE_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContextServiceAgreementId() {
    return contextServiceAgreementId;
  }


  public void setContextServiceAgreementId(String contextServiceAgreementId) {
    this.contextServiceAgreementId = contextServiceAgreementId;
  }


  public UserAccessLegalEntitiesAllOf userLegalEntityId(String userLegalEntityId) {
    
    this.userLegalEntityId = userLegalEntityId;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return userLegalEntityId
  **/
  @javax.annotation.Nullable
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_USER_LEGAL_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserLegalEntityId() {
    return userLegalEntityId;
  }


  public void setUserLegalEntityId(String userLegalEntityId) {
    this.userLegalEntityId = userLegalEntityId;
  }


  public UserAccessLegalEntitiesAllOf accessResourceType(AccessResourceType accessResourceType) {
    
    this.accessResourceType = accessResourceType;
    return this;
  }

   /**
   * Get accessResourceType
   * @return accessResourceType
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCESS_RESOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccessResourceType getAccessResourceType() {
    return accessResourceType;
  }


  public void setAccessResourceType(AccessResourceType accessResourceType) {
    this.accessResourceType = accessResourceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAccessLegalEntitiesAllOf userAccessLegalEntitiesAllOf = (UserAccessLegalEntitiesAllOf) o;
    return Objects.equals(this.contextServiceAgreementId, userAccessLegalEntitiesAllOf.contextServiceAgreementId) &&
        Objects.equals(this.userLegalEntityId, userAccessLegalEntitiesAllOf.userLegalEntityId) &&
        Objects.equals(this.accessResourceType, userAccessLegalEntitiesAllOf.accessResourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contextServiceAgreementId, userLegalEntityId, accessResourceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAccessLegalEntitiesAllOf {\n");
    sb.append("    contextServiceAgreementId: ").append(toIndentedString(contextServiceAgreementId)).append("\n");
    sb.append("    userLegalEntityId: ").append(toIndentedString(userLegalEntityId)).append("\n");
    sb.append("    accessResourceType: ").append(toIndentedString(accessResourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

