/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.AdditionalPropertiesAware;
import com.microsphere.accesscontrol.service.api.listener.v2.model.UserFunctionGroupsAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * UserFunctionGroups
 */
@JsonPropertyOrder({
  UserFunctionGroups.JSON_PROPERTY_ADDITIONS,
  UserFunctionGroups.JSON_PROPERTY_USER_ID,
  UserFunctionGroups.JSON_PROPERTY_FUNCTION_GROUP_IDS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class UserFunctionGroups {
  public static final String JSON_PROPERTY_ADDITIONS = "additions";
  private Map<String, String> additions = null;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private String userId;

  public static final String JSON_PROPERTY_FUNCTION_GROUP_IDS = "functionGroupIds";
  private List<String> functionGroupIds = null;


  public UserFunctionGroups additions(Map<String, String> additions) {
    
    this.additions = additions;
    return this;
  }

  public UserFunctionGroups putAdditionsItem(String key, String additionsItem) {
    if (this.additions == null) {
      this.additions = new HashMap<>();
    }
    this.additions.put(key, additionsItem);
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getAdditions() {
    return additions;
  }


  public void setAdditions(Map<String, String> additions) {
    this.additions = additions;
  }


  public UserFunctionGroups userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Internal id of the user.
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Internal id of the user.")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public UserFunctionGroups functionGroupIds(List<String> functionGroupIds) {
    
    this.functionGroupIds = functionGroupIds;
    return this;
  }

  public UserFunctionGroups addFunctionGroupIdsItem(String functionGroupIdsItem) {
    if (this.functionGroupIds == null) {
      this.functionGroupIds = new ArrayList<>();
    }
    this.functionGroupIds.add(functionGroupIdsItem);
    return this;
  }

   /**
   * List of internal function group ids.
   * @return functionGroupIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of internal function group ids.")
  @JsonProperty(JSON_PROPERTY_FUNCTION_GROUP_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getFunctionGroupIds() {
    return functionGroupIds;
  }


  public void setFunctionGroupIds(List<String> functionGroupIds) {
    this.functionGroupIds = functionGroupIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserFunctionGroups userFunctionGroups = (UserFunctionGroups) o;
    return Objects.equals(this.additions, userFunctionGroups.additions) &&
        Objects.equals(this.userId, userFunctionGroups.userId) &&
        Objects.equals(this.functionGroupIds, userFunctionGroups.functionGroupIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additions, userId, functionGroupIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserFunctionGroups {\n");
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    functionGroupIds: ").append(toIndentedString(functionGroupIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

