/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.Dataaccessgroupsforfunctionaccessgroupitem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * UsersGetResponseBody
 */
@JsonPropertyOrder({
  UsersGetResponseBody.JSON_PROPERTY_ID,
  UsersGetResponseBody.JSON_PROPERTY_USER_ID,
  UsersGetResponseBody.JSON_PROPERTY_SERVICE_AGREEMENT_ID,
  UsersGetResponseBody.JSON_PROPERTY_DATA_ACCESS_GROUPS_BY_FUNCTION_ACCESS_GROUP
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class UsersGetResponseBody {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  private String userId;

  public static final String JSON_PROPERTY_SERVICE_AGREEMENT_ID = "serviceAgreementId";
  private String serviceAgreementId;

  public static final String JSON_PROPERTY_DATA_ACCESS_GROUPS_BY_FUNCTION_ACCESS_GROUP = "dataAccessGroupsByFunctionAccessGroup";
  private List<Dataaccessgroupsforfunctionaccessgroupitem> dataAccessGroupsByFunctionAccessGroup = null;


  public UsersGetResponseBody id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return id
  **/
  @NotNull
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(required = true, value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public UsersGetResponseBody userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return userId
  **/
  @NotNull
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(required = true, value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public UsersGetResponseBody serviceAgreementId(String serviceAgreementId) {
    
    this.serviceAgreementId = serviceAgreementId;
    return this;
  }

   /**
   * Universally Unique Identifier.
   * @return serviceAgreementId
  **/
  @NotNull
 @Pattern(regexp="^[0-9a-f]{32}$|^[0-9a-f-]{36}$")  @ApiModelProperty(required = true, value = "Universally Unique Identifier.")
  @JsonProperty(JSON_PROPERTY_SERVICE_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getServiceAgreementId() {
    return serviceAgreementId;
  }


  public void setServiceAgreementId(String serviceAgreementId) {
    this.serviceAgreementId = serviceAgreementId;
  }


  public UsersGetResponseBody dataAccessGroupsByFunctionAccessGroup(List<Dataaccessgroupsforfunctionaccessgroupitem> dataAccessGroupsByFunctionAccessGroup) {
    
    this.dataAccessGroupsByFunctionAccessGroup = dataAccessGroupsByFunctionAccessGroup;
    return this;
  }

  public UsersGetResponseBody addDataAccessGroupsByFunctionAccessGroupItem(Dataaccessgroupsforfunctionaccessgroupitem dataAccessGroupsByFunctionAccessGroupItem) {
    if (this.dataAccessGroupsByFunctionAccessGroup == null) {
      this.dataAccessGroupsByFunctionAccessGroup = new ArrayList<>();
    }
    this.dataAccessGroupsByFunctionAccessGroup.add(dataAccessGroupsByFunctionAccessGroupItem);
    return this;
  }

   /**
   * Get dataAccessGroupsByFunctionAccessGroup
   * @return dataAccessGroupsByFunctionAccessGroup
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATA_ACCESS_GROUPS_BY_FUNCTION_ACCESS_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Dataaccessgroupsforfunctionaccessgroupitem> getDataAccessGroupsByFunctionAccessGroup() {
    return dataAccessGroupsByFunctionAccessGroup;
  }


  public void setDataAccessGroupsByFunctionAccessGroup(List<Dataaccessgroupsforfunctionaccessgroupitem> dataAccessGroupsByFunctionAccessGroup) {
    this.dataAccessGroupsByFunctionAccessGroup = dataAccessGroupsByFunctionAccessGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersGetResponseBody usersGetResponseBody = (UsersGetResponseBody) o;
    return Objects.equals(this.id, usersGetResponseBody.id) &&
        Objects.equals(this.userId, usersGetResponseBody.userId) &&
        Objects.equals(this.serviceAgreementId, usersGetResponseBody.serviceAgreementId) &&
        Objects.equals(this.dataAccessGroupsByFunctionAccessGroup, usersGetResponseBody.dataAccessGroupsByFunctionAccessGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, serviceAgreementId, dataAccessGroupsByFunctionAccessGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersGetResponseBody {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    serviceAgreementId: ").append(toIndentedString(serviceAgreementId)).append("\n");
    sb.append("    dataAccessGroupsByFunctionAccessGroup: ").append(toIndentedString(dataAccessGroupsByFunctionAccessGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

