/*
 * Access Control service API
 * Manage user permissions, data groups, function groups and service agreements from service to service side
 *
 * The version of the OpenAPI document: 2.11.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */


package com.microsphere.accesscontrol.service.api.listener.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.microsphere.accesscontrol.service.api.listener.v2.model.AdditionalPropertiesAware;
import com.microsphere.accesscontrol.service.api.listener.v2.model.UserPermissionsSummaryGetResponseBodyAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * UserPermissionsSummaryGetResponseBody
 */
@JsonPropertyOrder({
  UserPermissionsSummaryGetResponseBody.JSON_PROPERTY_ADDITIONS,
  UserPermissionsSummaryGetResponseBody.JSON_PROPERTY_RESOURCE,
  UserPermissionsSummaryGetResponseBody.JSON_PROPERTY_FUNCTION,
  UserPermissionsSummaryGetResponseBody.JSON_PROPERTY_PERMISSIONS
})
@javax.annotation.Generated(value = "com.backbase.oss.codegen.java.BoatJavaCodeGen", date = "2024-11-14T00:08:27.444046600+01:00[Africa/Tunis]")
public  class UserPermissionsSummaryGetResponseBody {
  public static final String JSON_PROPERTY_ADDITIONS = "additions";
  private Map<String, String> additions = null;

  public static final String JSON_PROPERTY_RESOURCE = "resource";
  private String resource;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  private String function;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  private Map<String, Boolean> permissions = new HashMap<>();


  public UserPermissionsSummaryGetResponseBody additions(Map<String, String> additions) {
    
    this.additions = additions;
    return this;
  }

  public UserPermissionsSummaryGetResponseBody putAdditionsItem(String key, String additionsItem) {
    if (this.additions == null) {
      this.additions = new HashMap<>();
    }
    this.additions.put(key, additionsItem);
    return this;
  }

   /**
   * Get additions
   * @return additions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getAdditions() {
    return additions;
  }


  public void setAdditions(Map<String, String> additions) {
    this.additions = additions;
  }


  public UserPermissionsSummaryGetResponseBody resource(String resource) {
    
    this.resource = resource;
    return this;
  }

   /**
   * Resource name
   * @return resource
  **/
  @NotNull
 @Size(min=1,max=32)  @ApiModelProperty(required = true, value = "Resource name")
  @JsonProperty(JSON_PROPERTY_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getResource() {
    return resource;
  }


  public void setResource(String resource) {
    this.resource = resource;
  }


  public UserPermissionsSummaryGetResponseBody function(String function) {
    
    this.function = function;
    return this;
  }

   /**
   * Business function name
   * @return function
  **/
  @NotNull
 @Size(min=1,max=32)  @ApiModelProperty(required = true, value = "Business function name")
  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFunction() {
    return function;
  }


  public void setFunction(String function) {
    this.function = function;
  }


  public UserPermissionsSummaryGetResponseBody permissions(Map<String, Boolean> permissions) {
    
    this.permissions = permissions;
    return this;
  }

  public UserPermissionsSummaryGetResponseBody putPermissionsItem(String key, Boolean permissionsItem) {
    this.permissions.put(key, permissionsItem);
    return this;
  }

   /**
   * Allowed user permissions
   * @return permissions
  **/
  @NotNull
  @ApiModelProperty(required = true, value = "Allowed user permissions")
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, Boolean> getPermissions() {
    return permissions;
  }


  public void setPermissions(Map<String, Boolean> permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPermissionsSummaryGetResponseBody userPermissionsSummaryGetResponseBody = (UserPermissionsSummaryGetResponseBody) o;
    return Objects.equals(this.additions, userPermissionsSummaryGetResponseBody.additions) &&
        Objects.equals(this.resource, userPermissionsSummaryGetResponseBody.resource) &&
        Objects.equals(this.function, userPermissionsSummaryGetResponseBody.function) &&
        Objects.equals(this.permissions, userPermissionsSummaryGetResponseBody.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additions, resource, function, permissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPermissionsSummaryGetResponseBody {\n");
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

